### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ArchieWalker** [reduxframework/ReduxCore#2]
firs of all, Thanks for the Great framework!

Ive been using it for some time now and on all websites I used Redux Framework with the theme, I always have the same problem. 

Advanced Custom Fields - options page is gone from the backend. If I type in the URL for the plugin, I can access it, add new fields etc, however, the menu items is gone from the menu list on the left side. 

I tried different page_priority numbers in the options-ini.php of the redux framework, no results. If I change the theme, ACF menu is visible again. 

Any ideas on how to fix it? 

Again, thanks for the amazing framework!

Regards,
Archie

**Comment by ArchieWalker** [comment]
No one here ever encountered this issue? :(

**Comment by ottok** [comment]
It looks like this project has been dead since 2013..

**Comment by kprovance** [comment]
This repository is no longer maintained.  Please see the redux-framework repository instead.  Thanks.
